### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by mforoughifar** [florafauna/optimParallel-R#3]
I am trying to use optimParallel to estimate the parameters of a model using maximum likelihood. But every time it gets into the following error (after running for a couple of iterations):

Error in stats::optim(par = par, fn = fg$f, gr = fg$g, method = "L-BFGS-B",  : 
  L-BFGS-B needs finite values of 'fn'
Calls: optimParallel -> <Anonymous>
Execution halted

I have tried many initial values but each time it comes to this error at some point in the process. Any suggestions? (Note: I am running the code on a university server in batch mode)

**Comment by blasif** [comment]
Hi, i'm an user also of optimparallel. It seems that you are getting Inf values for your optimization function at some point. (1) Could you double check, for example, by manually evaluating the loglik function at the boundaries set for the 'L-BFGS-B' optimization? (2) Could you double check if you maximizing or minimizing the function?

If you share me a fully reproducible code i can take a look.

Best!

**Comment by florafauna** [comment]
Please reopen if you can provide a reproducible example showing that `optim` works and `optimParallel` does not.
